### ISSUE TITLE
Clipper works when started manually, but not from unit file

### ISSUE THREAD

**Issue by ebyrne242** [wincent/clipper#17]
Clipper works when I start it manually, but from if I start it with the example unit file and the same config, it gives me an error when I try to copy to it (via unix socket).

$ systemctl --user start clipper
clipper: 2018/08/08 21:05:39 Starting UNIX domain socket server at /home/sketch/.ssh/clipper.sock
clipper: 2018/08/08 21:09:03 [ERROR] pipe copy: write |1: broken pipe
clipper: 2018/08/08 21:09:03 [ERROR] wait: exit status 1
clipper: 2018/08/08 21:09:03 Connection closed
[sketch@laptop ~]$ systemctl --user stop clipper
clipper: 2018/08/08 21:09:35 Got signal terminated
clipper: 2018/08/08 21:09:35 accept unix /home/sketch/.ssh/clipper.sock: use of closed network connection
[sketch@laptop ~]$ clipper
clipper: 2018/08/08 21:09:41 Starting UNIX domain socket server at /home/sketch/.ssh/clipper.sock
clipper: 2018/08/08 21:09:43 Echoed 4 bytes
clipper: 2018/08/08 21:09:43 Connection closed

**Comment by jeduardo** [comment]
@sketch242 this happens because clipper is using xclip underneath it and the `DISPLAY` environment variable in the unit file is most likely not matching your user display.

For example, this is the content of my `DISPLAY`environment variable:

```
$ echo $DISPLAY
:1
```

This is what is inside the unit file:
```
Environment=DISPLAY=:0
```

In my case I have changed `:0` to `:1` in the service unit file, ran a `systemctl --user daemon-reload && systemctl --user restart clipper.service` and I was then able to use clipper to inject data into the clipboard as expected.

**Comment by wincent** [comment]
Going to close this on the assumption that it is resolved.
