### ISSUE TITLE
Document caveats with BSD netcat vs GNU netcat vs socat etc

### ISSUE THREAD

**Issue by NightMachinery** [wincent/clipper#19]
nc has different implementations on different systems. Using gnu nc (which is installable by brew on any system) with the -c flag works best in my experience. This flag may not be present on other implementations or may not work correctly.

**Comment by wincent** [comment]
Platform differences are the main reason the `-executable` and `-flags` arguments are provided, so that people can make Clipper work on arbitrary systems. On the `nc` side, Clipper itself isn't going to get in your way if you want to invoke it one way or another. Are you suggesting that we make a note about the possible differences in `nc` in the docs somewhere? If so, what exactly would you suggest?

**Comment by NightMachinery** [comment]
Yeah, I suggest you recommend using gnu nc with the c flag on the docs, so
that things Just Work for new people.

**Comment by bradwood** [comment]
I agree... The brew-installed `nc  (netcat (The GNU Netcat) 0.7.1)` doesn't support `-U`. So it requires some digging around to make this work... I haven't figured this out yet, and will let you know once I do, but  it would be nice to update the readme at least.

**Comment by bradwood** [comment]
I ended up going with `socat - unix-client:/Users/brad/.clipper.sock` as gnu `nc` doesn't talk to Unix domain sockets from what I can tell and `socat` is brew-installable.

Now off to check vim-clipper...

**Comment by wincent** [comment]
As you will have seen, vim-clipper is making some assumptions about netcat:

https://github.com/wincent/vim-clipper/blob/35d15d7a096db63f1afce36f3dc1ae28dde4da98/autoload/clipper/private.vim#L5-L13

Namely, it invokes it as `nc $ADDRESS $PORT` if a port is supplied, and `nc -U $SOCKET` otherwise. Doesn't work at all if no `nc` available. Evidently needs to be made more configurable.

**Comment by wincent** [comment]
I added some notes to the docs which should be a good start. Please feel free to hit the edit button and create a PR if you can think of any further improvements.
